### ISSUE TITLE
Nextflow core/GitHub-URL runner

### ISSUE THREAD

**Issue by suecharo** [sapporo-wes/sapporo-service#18]
Want to add a runner to `run.sh` that will checkout the GitHub repository using GitHub-URL and run workflows.

**Comment by suecharo** [comment]
Also snakemake.

**Comment by inutano** [comment]
this one we need, unless the workflow-hub starts speaking the true TRS protocol

**Comment by suecharo** [comment]
See [Yevis Project](https://github.com/ddbj/yevis-cli)
