### ISSUE TITLE
Automatically discover the workflow engine versions?

### ISSUE THREAD

**Issue by kinow** [sapporo-wes/sapporo-service#27]
Hi!

I just solved an installation issue on my environment*, and now I have Sapporo Service and Sapporo Web running locally on my terminals, and I think I should be able to debug it too (that's how I normally get started with tools :)

The first thing I noticed was that Sapporo showed Toil and Nextflow in my test service, even though I don't have these installed in my Python virtual environment, nor on my local environment.

I think it would be useful if there was a way to specify manually what were the workflow engines, but also to automatically discover each engine (e.g. check if it can import some Python module, or locate an executable on `$PATH`.)

Thanks!
Bruno

*I was using miniconda, and apparently `uwsgi` cannot find `libpython`. I reverted to using Ubuntu's default Python, with a `venv` after installing `python-dev` for my Python version :+1: in case someone else has a similar issue.

**Comment by suecharo** [comment]
Hi Bruno-san (@kinow)

The workflow engine that can run is listed in [service-info.json](https://github.com/sapporo-wes/sapporo-service/blob/main/sapporo/service-info.json), and the actual running part is in [run.sh](https://github.com/sapporo-wes/sapporo-service/blob/main/sapporo/run.sh).
In `run.sh`, the workflow engine is run using docker sibling.
Therefore, even if the workflow engine is not installed locally, it is possible to run nextflow, etc.
If you wish to manually add the workflow engine, you can do so by editing these files.

> I think it would be useful if there was a way to specify manually what were the workflow engines, but also to automatically discover each engine (e.g. check if it can import some Python module, or locate an executable on $PATH.)

This is a good idea, but in order to support as many workflow engines as possible in sapporo-service, we are handling workflow engines in the above way.

> *I was using miniconda, and apparently uwsgi cannot find libpython. I reverted to using Ubuntu's default Python, with a venv after installing python-dev for my Python version 👍 in case someone else has a similar issue.

Dependencies in Python libraries are difficult...
We are trying to deal with them as much as possible...
If you do not want to use `uwsgi` , `pip install sapporo` will install the `sapporo` command so that you can run `sapporo-service` using only `flask`.

**Comment by kinow** [comment]
Hi Suetake-San :wave: 

> If you wish to manually add the workflow engine, you can do so by editing these files.

Ah! True, Manabu had told me but I forgot that, sorry.

At my previous work researchers had access to the national supercomputer infrastructure, where workflow managers (Cylc, Snakemake, Nextflow, etc) would be installed in their VM's and loaded via modules.

They were introducing containers, but Docker was strictly prohibited and only Singularity was allowed. I had a look at Sapporo Service and I think Singularity is not yet supported, only Docker.

Maybe we can close this issue, and alter this paragraph (or add somewhere near the top of the readme) adding the following info:

“One of sapporo-service's features is the abstraction of workflow engines, making it easy to convert various workflow engines into WES. Workflow engines are executed with by sapporo-service using Docker (i.e. it does not use the versions you have on `$PATH`). Currently, the following workflow engines have been confirmed to work.”

Or something along those lines. I think further down what you explained to me is also detailed in the README near the part about `run.sh` (should have read that first, sorry.) WDYT?

>This is a good idea, but in order to support as many workflow engines as possible in sapporo-service, we are handling workflow engines in the above way.

:+1: 

>Dependencies in Python libraries are difficult...
>We are trying to deal with them as much as possible...
>If you do not want to use uwsgi , pip install sapporo will install the sapporo command so that you can run sapporo-service using only flask.

Ah, good tip!

Thanks!!! :bow: 
Bruno

**Comment by inutano** [comment]
Thanks @kinow, and glad to hear that you successfully installed sapporo-service! Totally agree with adding the lines explaining the engines and run.sh to README as well. Feel free to send a PR to edit it!

> They were introducing containers, but Docker was strictly prohibited and only Singularity was allowed. I had a look at Sapporo Service and I think Singularity is not yet supported, only Docker. I think in their case, Sapporo would not be an option for now due to the exclusive use of Docker (which they may change later, I like this feature as it makes it easier for the devs to maintain Sapporo :)

Pretty understandable. Our initial concept was that the admin is responsible to install Sapporo system to the shared computing cluster, then the users will use it via the internet. But now we have the rootless Docker and @suecharo confirmed that sapporo can work with it, so time will solve the issue, I hope.

I'm quite doubtful about the sustainability of the Singularity project, so not feeling like we do something with it btw.
