### ISSUE TITLE
WES 1.1.0 `worfklow_engine`

### ISSUE THREAD

**Issue by ericenns** [sapporo-wes/sapporo-service#37]
Now that WES 1.1.0 is out and has `workflow_engine` could `workflow_engine_name` be removed or just update to allow client to use `workflow_engine` which is the same as sapporo's customized `workflow_engine_name`.

https://ga4gh.github.io/workflow-execution-service-schemas/docs/

**Comment by inutano** [comment]
@ericenns Great, we should follow the update! 

@suecharo Do you see any conflicts with the other products? [yevis-cli](https://github.com/sapporo-wes/yevis-cli) would need a change as well
